# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

apiVersion: v1
kind: Service
metadata:
  name: aiservice-service
  namespace: ns-esg-docanalysis
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: aiservice
---
apiVersion: v1
kind: Service
metadata:
  name: kernelmemory-service
  namespace: ns-esg-docanalysis
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app: kernelmemory

